name: Validate CI Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets presence
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_PROJECT_MOBILE: ${{ secrets.SENTRY_PROJECT_MOBILE }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Checking CI/CD secrets..."
          for name in VERCEL_TOKEN RENDER_API_KEY RENDER_SERVICE_ID EAS_TOKEN SENTRY_AUTH_TOKEN SENTRY_ORG SENTRY_PROJECT SENTRY_PROJECT_MOBILE STRIPE_SECRET_KEY SUPABASE_URL SUPABASE_KEY; do
            val=$(printenv $name || true)
            if [ -z "$val" ]; then
              echo "MISSING: $name"
            else
              echo "OK: $name"
            fi
          done


